import type { components } from './schema';

// Contract-derived domain types — the single source of truth for shapes the
// backend reads and returns. Generated by `npm run gen:api`.
export type EventType = components['schemas']['EventType'];
export type Slot = components['schemas']['Slot'];
export type Booking = components['schemas']['Booking'];
export type AvailabilitySchedule =
  components['schemas']['AvailabilitySchedule'];
export type DayAvailability = components['schemas']['DayAvailability'];
export type TimeRange = components['schemas']['TimeRange'];
export type Weekday = components['schemas']['Weekday'];
export type ApiError = components['schemas']['ApiError'];
