/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/availability': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get the owner's weekly availability schedule. */
    get: operations['Availability_get'];
    /** @description Replace the owner's weekly availability schedule. */
    put: operations['Availability_replace'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/bookings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Owner: list all upcoming bookings across every event type. */
    get: operations['Bookings_list'];
    put?: never;
    /** @description Guest: book a free slot. */
    post: operations['Bookings_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/event-types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description List all event types (owner admin + guest catalog). */
    get: operations['EventTypes_list'];
    put?: never;
    /** @description Create an event type (owner). */
    post: operations['EventTypes_create'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/event-types/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Get a single event type by id (guest booking page). */
    get: operations['EventTypes_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/event-types/{id}/slots': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * @description List slots for an event type. Defaults to the rolling 14-day window from
     *     today; `from`/`to` may narrow it (UTC, ISO 8601).
     */
    get: operations['EventTypes_listSlots'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @description Machine-readable error returned for non-2xx responses. */
    ApiError: {
      /** @description Stable error code, e.g. "not_found", "slot_taken", "duplicate_id". */
      code: string;
      /** @description Human-readable explanation. */
      message: string;
    };
    /** @description The owner's recurring weekly availability. */
    AvailabilitySchedule: {
      /** @description IANA timezone the working hours are interpreted in (e.g. "Europe/Moscow"). */
      timezone: string;
      /** @description Working hours per weekday. */
      week: components['schemas']['DayAvailability'][];
    };
    BadRequestError: components['schemas']['ApiError'];
    /** @description A confirmed reservation of a slot by a guest. */
    Booking: {
      /** @description Server-generated identifier. */
      id: string;
      eventTypeId: string;
      guestName: string;
      guestEmail: string;
      /** Format: date-time */
      start: string;
      /**
       * Format: date-time
       * @description = start + event type durationMinutes.
       */
      end: string;
    };
    /** @description Payload a guest submits to book a slot. The server computes `end`. */
    BookingCreate: {
      eventTypeId: string;
      guestName: string;
      guestEmail: string;
      /**
       * Format: date-time
       * @description Start of the chosen slot (ISO 8601, UTC). Must match an available slot.
       */
      start: string;
    };
    ConflictError: components['schemas']['ApiError'];
    /** @description Working intervals for a single weekday. An empty list means a day off. */
    DayAvailability: {
      weekday: components['schemas']['Weekday'];
      ranges: components['schemas']['TimeRange'][];
    };
    /** @description A type of meeting the owner offers (e.g. "Intro call"). */
    EventType: {
      /** @description Owner-assigned slug, unique across event types (e.g. "intro-call"). */
      id: string;
      title: string;
      description: string;
      /**
       * Format: int32
       * @description Meeting length in minutes; must be a positive multiple of 30.
       */
      durationMinutes: number;
    };
    /** @description Payload to create an event type. The owner assigns the `id`. */
    EventTypeCreate: {
      /** @description Owner-assigned slug, unique across event types (e.g. "intro-call"). */
      id: string;
      title: string;
      description: string;
      /**
       * Format: int32
       * @description Meeting length in minutes; must be a positive multiple of 30.
       */
      durationMinutes: number;
    };
    NotFoundError: components['schemas']['ApiError'];
    /** @description A candidate booking slot for an event type. */
    Slot: {
      /**
       * Format: date-time
       * @description Slot start (ISO 8601, UTC).
       */
      start: string;
      /**
       * Format: date-time
       * @description Slot end (ISO 8601, UTC), = start + event type durationMinutes.
       */
      end: string;
      /** @description False when the slot overlaps an existing booking of any event type. */
      available: boolean;
    };
    /** @description A working interval within a day, expressed in the schedule's timezone. */
    TimeRange: {
      /** @description Inclusive start time, "HH:MM" 24-hour (e.g. "09:00"). */
      start: string;
      /** @description Exclusive end time, "HH:MM" 24-hour (e.g. "17:00"). */
      end: string;
    };
    /** @enum {string} */
    Weekday:
      | 'monday'
      | 'tuesday'
      | 'wednesday'
      | 'thursday'
      | 'friday'
      | 'saturday'
      | 'sunday';
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  Availability_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AvailabilitySchedule'];
        };
      };
    };
  };
  Availability_replace: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AvailabilitySchedule'];
      };
    };
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AvailabilitySchedule'];
        };
      };
      /** @description The server could not understand the request due to invalid syntax. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
    };
  };
  Bookings_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Booking'][];
        };
      };
    };
  };
  Bookings_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BookingCreate'];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Booking'];
        };
      };
      /** @description The server could not understand the request due to invalid syntax. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description The server cannot find the requested resource. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotFoundError'];
        };
      };
      /** @description The request conflicts with the current state of the server. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConflictError'];
        };
      };
    };
  };
  EventTypes_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventType'][];
        };
      };
    };
  };
  EventTypes_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EventTypeCreate'];
      };
    };
    responses: {
      /** @description The request has succeeded and a new resource has been created as a result. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventType'];
        };
      };
      /** @description The server could not understand the request due to invalid syntax. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BadRequestError'];
        };
      };
      /** @description The request conflicts with the current state of the server. */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConflictError'];
        };
      };
    };
  };
  EventTypes_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['EventType'];
        };
      };
      /** @description The server cannot find the requested resource. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotFoundError'];
        };
      };
    };
  };
  EventTypes_listSlots: {
    parameters: {
      query?: {
        from?: string;
        to?: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The request has succeeded. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Slot'][];
        };
      };
      /** @description The server cannot find the requested resource. */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotFoundError'];
        };
      };
    };
  };
}
